CREATE TABLE user (
    id INTEGER NOT NULL PRIMARY KEY,
    username VARCHAR(12) NOT NULL,
    passwrd VARCHAR(43) NOT NULL,
    email VARCHAR (320) NOT NULL,
    joined DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);